[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.139.2",
    "langchain-huggingface>=1.2.2",
    "passlib[bcrypt]>=1.7.4",
    "pymongo>=4.17.0",
    "python-jose[cryptography]>=3.5.0",
    "sentence-transformers>=5.6.0",
    "uvicorn[standard]>=0.51.0",
    "weaviate-client>=4.22.0",
]
